on:
  push:
    branches:
      - main

name: Build and publish extension to browser stores

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - firefox
          - chrome
    env:
      TARGET: ${{ matrix.target }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Check if new package version
        id: check_version
        uses: johnnybenson/package-json-versioned-action@v1.0.8
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the extension for ${{ matrix.target }}
        if: steps.check_version.outputs.has-updated == 'true' || matrix.target == 'chrome'
        run: pnpm build:${{ matrix.target }}

      - name: Publish to AMO
        if: |
          steps.check_version.outputs.has-updated == 'true' &&
          matrix.target == 'firefox'
        run: pnpm sign
        env:
          AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
          AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}

      - name: Publish to Chrome Web store
        if: |
          matrix.target == 'chrome'
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          extension-id: ${{ secrets.GWS_EXTENSION_ID }}
          client-id: ${{ secrets.GWS_CLIENT_ID }}
          client-secret: ${{ secrets.GWS_CLIENT_SECRET }}
          refresh-token: ${{ secrets.GWS_REFRESH_TOKEN }}
          glob: true
          file-path: dist/anti-clickbait-*.zip
